[build]
  command = "npm run build"
  publish = ".next"
  functions = "netlify/functions"

[[plugins]]
  package = "@netlify/next"

[dev]
  functions = "netlify/functions"
  port = 8888  
  targetPort = 3000
